
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Dec 07 01:37:35 CST 2015
//----------------------------------------------------

package fase1;

/** CUP generated class containing symbol constants. */
public class sF1 {
  /* terminals */
  public static final int vacioL = 7;
  public static final int boolL = 6;
  public static final int parC = 44;
  public static final int menor = 62;
  public static final int repite = 22;
  public static final int parA = 43;
  public static final int yLogico = 54;
  public static final int comparacion = 57;
  public static final int supeL = 39;
  public static final int punto = 42;
  public static final int nulo = 33;
  public static final int decremento = 69;
  public static final int casteoDouble = 28;
  public static final int sobreescritura = 40;
  public static final int importar = 37;
  public static final int suma = 63;
  public static final int interruptor = 15;
  public static final int div = 66;
  public static final int resta = 64;
  public static final int dosPuntos = 50;
  public static final int cadena = 75;
  public static final int mientras = 20;
  public static final int corC = 48;
  public static final int imprimir = 26;
  public static final int corA = 47;
  public static final int privado = 35;
  public static final int menorIgual = 60;
  public static final int detener = 18;
  public static final int sino = 13;
  public static final int pordefecto = 17;
  public static final int decimal = 71;
  public static final int encaso = 16;
  public static final int casteoDString = 30;
  public static final int sinosi = 14;
  public static final int casteoInt = 27;
  public static final int xorLogico = 56;
  public static final int caracter = 73;
  public static final int asignacion = 51;
  public static final int nuevo = 8;
  public static final int id = 72;
  public static final int retorno = 32;
  public static final int casteoIString = 29;
  public static final int mayorIgual = 59;
  public static final int herencia = 38;
  public static final int path = 74;
  public static final int protegido = 36;
  public static final int llaveC = 46;
  public static final int mayor = 61;
  public static final int llaveA = 45;
  public static final int cadenaL = 4;
  public static final int EOF = 0;
  public static final int casteoDI = 31;
  public static final int clasesL = 9;
  public static final int falso = 10;
  public static final int este = 41;
  public static final int publico = 34;
  public static final int puntoComa = 52;
  public static final int verdadero = 11;
  public static final int error = 1;
  public static final int continuar = 19;
  public static final int si = 12;
  public static final int negacion = 53;
  public static final int caracterL = 5;
  public static final int hacer = 21;
  public static final int doubleL = 3;
  public static final int distinto = 58;
  public static final int pot = 67;
  public static final int por = 65;
  public static final int ciclo = 25;
  public static final int para = 24;
  public static final int enteroL = 2;
  public static final int coma = 49;
  public static final int oLogico = 55;
  public static final int incremento = 68;
  public static final int num = 70;
  public static final int hasta = 23;
}

